data:
  sequence_iterator:
    classname: SleeperTokenSequenceLoader
    kwargs:
      include_sleeper_data: false
      sequence_length: 128
      shuffle_buffer_size: 1024
  activations_harvester:
    harvesting_batch_size: 16
    llms:
      - name: "roneneldan/TinyStories-Instruct-33M"
        lora_name: "mars-jason-25/tiny-stories-33M-TSdata-sleeper"
  activations_shuffle_buffer_size: 1024
  n_batches_for_norm_estimate: 1 # unnecessary since will be overridden
wandb:
  entity: "dmitry2-uiuc"
  project: "sleeper-model-diffing"
experiment_name: "crosscoder_M"
crosscoder:
  hidden_dim: 1536
  ft_init_checkpt_folder: ".checkpoints/crosscoder_S_2025-02-22_09-50-13/"
  ft_init_checkpt_step: 39999
  jumprelu:
    backprop_through_jumprelu_input: true
train:
  batch_size: 256
  optimizer:
    initial_learning_rate: 1e-4
    last_pct_of_steps: 0.2
  num_steps: 10000
  save_every_n_steps: 10000
  log_every_n_steps: 50
  initial_lambda_s: 0.5
  final_lambda_s: 0.5
hookpoints:
  - "blocks.0.hook_resid_pre"
  #- "blocks.0.hook_resid_mid"
  - "blocks.0.hook_resid_post"
  #- "blocks.1.hook_resid_pre"
  #- "blocks.1.hook_resid_mid"
  - "blocks.1.hook_resid_post"
  #- "blocks.2.hook_resid_pre"
  #- "blocks.2.hook_resid_mid"
  - "blocks.2.hook_resid_post"
  #- "blocks.3.hook_resid_pre"
  #- "blocks.3.hook_resid_mid"
  - "blocks.3.hook_resid_post"
